apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: drapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: drapi
        service: webapi
    spec:
      containers:
        - name: webapi
          image: drapi.azurecr.io/drapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP